# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      
    - name: Select Xcode 16.4
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app
      
    - name: Build 
      run: swift build -v
    - name: Run tests
      run: swift test -v
